variable "ami" {}
variable "key_name" {}
variable "public_key_path" {}
variable "instance_type" {}
variable "server_security_group" {}
variable "client_security_group" {}
variable "public_subnet_a" {}
variable "public_subnet_b" {}
variable "public_subnet_c" {}
variable "private_subnet_a" {}
variable "private_subnet_b" {}
variable "private_subnet_c" {}
variable "elb_security_group" {}
variable "aws_profile" {}
